package com.androidfinalproject.hacktok.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF1877F2)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD0E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF002F6C)
val md_theme_light_secondary = Color(0xFF606770)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF0F2F5)
val md_theme_light_onSecondaryContainer = Color(0xFF1C1E21)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF1C1E21)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1C1E21)
val md_theme_light_surfaceVariant = Color(0xFFE4E6EB)
val md_theme_light_onSurfaceVariant = Color(0xFF65676B)

val md_theme_dark_primary = Color(0xFF1B74E4)
val md_theme_dark_onPrimary = Color(0xFFD0E4FF)
val md_theme_dark_primaryContainer = Color(0xFF002F6C)
val md_theme_dark_onPrimaryContainer = Color(0xFFD0E4FF)
val md_theme_dark_secondary = Color(0xFFB0B3B8)
val md_theme_dark_onSecondary = Color(0xFF18191A)
val md_theme_dark_secondaryContainer = Color(0xFF3A3B3C)
val md_theme_dark_onSecondaryContainer = Color(0xFFE4E6EB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF18191A)
val md_theme_dark_onBackground = Color(0xFFE4E6EB)
val md_theme_dark_surface = Color(0xFF242526)
val md_theme_dark_onSurface = Color(0xFFE4E6EB)
val md_theme_dark_surfaceVariant = Color(0xFF3A3B3C)
val md_theme_dark_onSurfaceVariant = Color(0xFFB0B3B8)

val google_blue = Color(0xFF4285F4)
val google_red = Color(0xFFDB4437)
val google_yellow = Color(0xFFF4B400)
val google_green = Color(0xFF0F9D58)
